name: Go Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go environment
      uses: actions/setup-go@v3.3.1
      with:
      # Path to the go.mod file.
        go-version-file: ./mttp/go.mod
    

    - name: Test
      run: go test -v ./mttp/...
